Protege rotas de seleção de condomínios
TreinaDev/pague-aluguel pull request #113
Opened 2024-07-18 19:53 UTC by NathanaelV

2024-07-18 22:53 UTC, kanzakisuemi approved these changes

2024-07-18 22:53 UTC, kanzakisuemi commented on app/controllers/common_areas_controller.rb
esse método `admin_authorized?` já está sendo usado acredito q no `condos_controller` e já percebi q precisaremos dele tb no `bills_controller`, não seria o caso d por esse método no `application_controller` já que todos herdam dele?

2024-07-19 00:02 UTC, mbellucio requested changes
Acho aqui aqui vale criar um controller personalizado que herda de application controller, dai todos esses controllers que tem autorização idêntica herdam desse novo controller customizado.

2024-07-19 13:13 UTC, NathanaelV commented on app/controllers/common_areas_controller.rb
O método `admin_authorized?` que está em `condos_controller.rb` usa `params[:id]`. Os outros métodos usam `params[:condo_id]`, por isso serão necessários dois métodos.

Porém adicionei o método que usa o `params[:id]` ao `application_controller.rb`, pois usaremos em outras classes.

2024-07-19 13:16 UTC, NathanaelV commented
> Acho aqui aqui vale criar um controller personalizado que herda de application controller, dai todos esses controllers que tem autorização idêntica herdam desse novo controller customizado.

Achei melhor só adicionar o método ao `ApplicationController`, pois se trata de só um método. Caso houvessem mais métodos valeria a pena criar um controller só para autorização.

2024-07-19 14:34 UTC, mbellucio approved these changes

2024-07-19 14:36 UTC, merged