Cadastro de Taxas Limitadas
TreinaDev/pague-aluguel pull request #55
Opened 2024-07-05 15:58 UTC by LaiLestrange

Funcionalidade: Administrador agora pode definir a quantidade de recorrências de uma taxa condominial, podendo assim criar uma taxa limitada.

O que já foi feito:
- Modificamos o model base_fee para trabalhar com taxas condominiais tanto fixas quanto limitadas
- Corrigimos a Implementação do I18n
- Refatoramos o título do formulário
- Refatoramos a exibição do tipo de taxa na tela de detalhes

Onde estamos atuando:
- Implementação do campo para inserção da quantidade de parcelas caso a taxa seja limitada

O que vem pela frente:
- Ajustes dos testes já existentes e adição de outros testes para garantir a cobertura do código.

![image](https://github.com/TreinaDev/pague-aluguel/assets/27514762/4db8bad6-4f0b-4b68-b478-ef325a4574c6)
(exibição do tipo de taxa logo abaixo do título)
![image](https://github.com/TreinaDev/pague-aluguel/assets/27514762/acc91467-175e-433e-886f-3889f21c0aa7)
(título e checkbox alterados para refletirem a intenção do formulário)

2024-07-05 21:47 UTC, mbellucio requested changes
Não encontrei nenhum problema nas mudanças implementadas, tudo parece estar correto. Só alterem o teste que está pending.

2024-07-05 21:47 UTC, mbellucio commented on spec/system/visitor_views_home_spec.rb
João na primeira semana mencionou para mim e para o Nathan não deixarmos testes pendentes desta forma. É melhor fazer o teste passar ou deletar estes testes.

2024-07-06 13:28 UTC, LaiLestrange commented on spec/system/visitor_views_home_spec.rb
Faz sentido, Matheus. Quando implementamos o Stimulus, os testes de tela inicial começaram a quebrar. Vamos resolver isso em breve. Obrigada!

2024-07-08 13:40 UTC, Arthorioscal commented on app/javascript/controllers/hello_controller.js
Esse controller aqui tem alguma funcionalidade na aplicação?

2024-07-08 13:42 UTC, LaiLestrange commented on app/javascript/controllers/hello_controller.js
Não tem, acredito que tenha sido um arquivo gerado automaticamente pelo stimulus. Vamos ver direitinho. Obrigada!

2024-07-08 13:46 UTC, Arthorioscal approved these changes
Bom trabalho pessoal! Eu só deixei de comentário sobre aquele controller com 'Hello World' que não entendi a funcionalidade dele, fora isso tá tudo perfeito! boa :)

2024-07-08 18:59 UTC, angelomaia commented on spec/system/visitor_views_home_spec.rb
Quando fizemos o merge da nova main na branch hoje mais cedo, esses testes foram corrigidos. =]

2024-07-08 19:21 UTC, angelomaia commented on app/javascript/controllers/hello_controller.js
Também acho que ele foi gerado quando instalamos o Stimulus. Retiramos esse arquivo no último commit!

2024-07-08 20:57 UTC, mbellucio approved these changes

2024-07-09 09:58 UTC, merged